title: lld_practice
author: Vaibhav Bansal
copyright: "2026"

execute:
  execute_notebooks: off

repository:
  url: https://github.com/VaibhavBansal26/lld_practice
  path_to_book: ""
  branch: main

html:
  use_repository_button: true
  use_issues_button: false